INSERT INTO fa_gender (gender, description) VALUES ('M', 'Male');
INSERT INTO fa_gender (gender, description) VALUES ('F', 'Female');

INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AFG', 'Afghanistan', 1068, 145);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AIA', 'Anguilla', 868, 208);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ALB', 'Albania', 1383, 60);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ALG', 'Algeria', 1343, 67);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AND', 'Andorra', 1121, 133);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ANG', 'Angola', 1108, 130);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ARG', 'Argentina', 1575, 12);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ARM', 'Armenia', 1225, 101);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ARU', 'Aruba', 924, 185);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ASA', 'American Samoa', 908, 192);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ATG', 'Antigua and Barbuda', 1122, 126);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AUS', 'Australia', 1431, 42);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AUT', 'Austria', 1499, 24);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('AZE', 'Azerbaijan', 1202, 107);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BAH', 'Bahamas', 862, 210);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BAN', 'Bangladesh', 907, 194);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BDI', 'Burundi', 1061, 142);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BEL', 'Belgium', 1729, 1);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BEN', 'Benin', 1273, 87);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BER', 'Bermuda', 940, 180);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BFA', 'Burkina Faso', 1391, 57);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BHR', 'Bahrain', 1181, 113);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BHU', 'Bhutan', 917, 188);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BIH', 'Bosnia and Herzegovina', 1468, 32);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BLR', 'Belarus', 1304, 78);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BLZ', 'Belize', 1004, 164);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BOL', 'Bolivia', 1378, 59);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BOT', 'Botswana', 1077, 140);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BRA', 'Brazil', 1663, 3);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BRB', 'Barbados', 1003, 162);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BRU', 'Brunei Darussalam', 903, 196);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('BUL', 'Bulgaria', 1430, 45);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CAM', 'Cambodia', 979, 170);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CAN', 'Canada', 1307, 76);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CAY', 'Cayman Islands', 878, 203);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CGO', 'Congo', 1289, 87);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CHA', 'Chad', 956, 174);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CHI', 'Chile', 1568, 13);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CHN', 'China PR', 1313, 75);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CIV', 'Côte d''Ivoire', 1351, 64);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CMR', 'Cameroon', 1408, 51);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('COD', 'Congo DR', 1447, 46);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('COK', 'Cook Islands', 908, 192);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('COL', 'Colombia', 1567, 11);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('COM', 'Comoros', 1060, 148);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CPV', 'Cape Verde Islands', 1350, 68);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CRC', 'Costa Rica', 1460, 37);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CRO', 'Croatia', 1634, 4);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CTA', 'Central African Republic', 1187, 113);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CUB', 'Cuba', 946, 177);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CUW', 'Curaçao', 1303, 79);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CYP', 'Cyprus', 1283, 86);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('CZE', 'Czech Republic', 1418, 48);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('DEN', 'Denmark', 1581, 10);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('DJI', 'Djibouti', 896, 197);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('DMA', 'Dominica', 953, 178);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('DOM', 'Dominican Republic', 1040, 152);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ECU', 'Ecuador', 1378, 61);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('EGY', 'Egypt', 1364, 58);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ENG', 'England', 1612, 5);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('EQG', 'Equatorial Guinea', 1086, 146);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ERI', 'Eritrea', 868, 204);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ESP', 'Spain', 1597, 9);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('EST', 'Estonia', 1240, 98);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ETH', 'Ethiopia', 1060, 150);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('FIJ', 'Fiji', 981, 167);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('FIN', 'Finland', 1378, 56);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('FRA', 'France', 1729, 2);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('FRO', 'Faroe Islands', 1261, 95);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GAB', 'Gabon', 1274, 83);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GAM', 'Gambia', 972, 173);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GEO', 'Georgia', 1254, 92);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GER', 'Germany', 1568, 14);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GHA', 'Ghana', 1407, 52);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GIB', 'Gibraltar', 891, 190);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GNB', 'Guinea-Bissau', 1149, 119);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GRE', 'Greece', 1433, 42);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GRN', 'Grenada', 976, 172);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GUA', 'Guatemala', 1064, 147);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GUI', 'Guinea', 1353, 65);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GUM', 'Guam', 907, 194);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('GUY', 'Guyana', 937, 179);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('HAI', 'Haiti', 1212, 103);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('HKG', 'Hong Kong', 1076, 144);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('HON', 'Honduras', 1368, 62);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('HUN', 'Hungary', 1409, 55);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('IDN', 'Indonesia', 997, 160);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('IND', 'India', 1244, 97);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('IRL', 'Republic of Ireland', 1478, 33);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('IRN', 'IR Iran', 1474, 30);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('IRQ', 'Iraq', 1272, 89);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ISL', 'Iceland', 1461, 36);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ISR', 'Israel', 1247, 91);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ITA', 'Italy', 1526, 19);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('JAM', 'Jamaica', 1401, 53);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('JOR', 'Jordan', 1189, 112);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('JPN', 'Japan', 1398, 50);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KAZ', 'Kazakhstan', 1160, 117);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KEN', 'Kenya', 1204, 105);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KGZ', 'Kyrgyz Republic', 1265, 90);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KOR', 'Korea Republic', 1395, 53);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KSA', 'Saudi Arabia', 1337, 72);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KUW', 'Kuwait', 1014, 157);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('KVX', 'Kosovo', 1092, 137);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LAO', 'Laos', 946, 181);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LBR', 'Liberia', 1023, 154);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LBY', 'Libya', 1226, 105);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LCA', 'St Lucia', 982, 168);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LES', 'Lesotho', 1070, 149);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LIB', 'Lebanon', 1308, 82);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LIE', 'Liechtenstein', 947, 182);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LTU', 'Lithuania', 1123, 129);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LUX', 'Luxembourg', 1292, 84);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('LVA', 'Latvia', 1116, 132);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MAC', 'Macau', 925, 184);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MAD', 'Madagascar', 1205, 100);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MAR', 'Morocco', 1425, 47);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MAS', 'Malaysia', 972, 169);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MDA', 'Moldova', 958, 171);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MDV', 'Maldives', 1049, 151);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MEX', 'Mexico', 1550, 16);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MKD', 'FYR Macedonia', 1344, 68);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MLI', 'Mali', 1365, 66);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MLT', 'Malta', 928, 183);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MNE', 'Montenegro', 1444, 39);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MNG', 'Mongolia', 922, 186);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MOZ', 'Mozambique', 1175, 122);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MRI', 'Mauritius', 1022, 156);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MSR', 'Montserrat', 870, 202);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MTN', 'Mauritania', 1217, 104);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MWI', 'Malawi', 1129, 125);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('MYA', 'Myanmar', 1092, 141);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NAM', 'Namibia', 1170, 109);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NCA', 'Nicaragua', 1121, 127);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NCL', 'New Caledonia', 1032, 155);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NED', 'Netherlands', 1540, 15);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NEP', 'Nepal', 1004, 161);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NGA', 'Nigeria', 1415, 44);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NIG', 'Niger', 1207, 108);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NIR', 'Northern Ireland', 1487, 34);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NOR', 'Norway', 1405, 48);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('NZL', 'New Zealand', 1157, 119);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('OMA', 'Oman', 1287, 84);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PAK', 'Pakistan', 890, 199);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PAN', 'Panama', 1339, 70);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PAR', 'Paraguay', 1477, 31);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PER', 'Peru', 1525, 20);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PHI', 'Philippines', 1172, 116);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PLE', 'Palestine', 1225, 99);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PNG', 'Papua New Guinea', 984, 166);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('POL', 'Poland', 1537, 21);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('POR', 'Portugal', 1606, 7);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PRK', 'Korea DPR', 1196, 110);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('PUR', 'Puerto Rico', 955, 175);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('QAT', 'Qatar', 1247, 96);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ROU', 'Romania', 1489, 26);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('RSA', 'South Africa', 1325, 73);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('RUS', 'Russia', 1423, 41);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('RWA', 'Rwanda', 1093, 138);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SAM', 'Samoa', 896, 197);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SCO', 'Scotland', 1448, 40);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SDN', 'Sudan', 1114, 135);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SEN', 'Senegal', 1492, 25);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SEY', 'Seychelles', 913, 188);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SIN', 'Singapore', 982, 165);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SKN', 'St Kitts and Nevis', 1109, 133);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SLE', 'Sierra Leone', 1172, 115);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SLV', 'El Salvador', 1332, 70);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SMR', 'San Marino', 871, 209);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SOL', 'Solomon Islands', 1073, 143);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SOM', 'Somalia', 868, 204);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SRB', 'Serbia', 1463, 35);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SRI', 'Sri Lanka', 890, 201);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SSD', 'South Sudan', 1019, 159);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('STP', 'São Tomé e Príncipe', 920, 187);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SUI', 'Switzerland', 1598, 8);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SUR', 'Suriname', 1035, 153);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SVK', 'Slovakia', 1491, 28);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SVN', 'Slovenia', 1376, 62);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SWE', 'Sweden', 1550, 17);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SWZ', 'Eswatini', 1101, 139);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('SYR', 'Syria', 1322, 74);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TAH', 'Tahiti', 1020, 157);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TAN', 'Tanzania', 1089, 136);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TCA', 'Turks and Caicos Islands', 862, 211);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TGA', 'Tonga', 868, 204);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('THA', 'Thailand', 1144, 121);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TJK', 'Tajikistan', 1156, 118);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TKM', 'Turkmenistan', 1120, 128);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TLS', 'Timor-Leste', 909, 191);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TOG', 'Togo', 1139, 123);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TPE', 'Chinese Taipei', 1139, 124);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TRI', 'Trinidad and Tobago', 1269, 93);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TUN', 'Tunisia', 1503, 22);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('TUR', 'Turkey', 1456, 38);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('UAE', 'United Arab Emirates', 1308, 81);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('UGA', 'Uganda', 1291, 79);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('UKR', 'Ukraine', 1483, 27);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('URU', 'Uruguay', 1632, 6);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('USA', 'USA', 1510, 23);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('UZB', 'Uzbekistan', 1245, 94);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VAN', 'Vanuatu', 1000, 162);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VEN', 'Venezuela', 1476, 29);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VGB', 'British Virgin Islands', 872, 207);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VIE', 'Vietnam', 1220, 102);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VIN', 'St Vincent and the Grenadines', 955, 175);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('VIR', 'US Virgin Islands', 889, 200);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('WAL', 'Wales', 1536, 18);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('YEM', 'Yemen', 1112, 131);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ZAM', 'Zambia', 1316, 77);
INSERT INTO fa_country (country_code, country_name, points, rank) VALUES ('ZIM', 'Zimbabwe', 1167, 110);

INSERT INTO fa_source (source, description) VALUES ('OPTA', 'Opta Source');
INSERT INTO fa_source (source, description) VALUES ('SCOUT7', 'Scout7 Source');
INSERT INTO fa_source (source, description) VALUES ('PMA', 'PMA Source');
INSERT INTO fa_source (source, description) VALUES ('INTERNAL', 'PPS Internal Source');

INSERT INTO fa_squad_status (status, description) VALUES ('LONG_LIST', 'Long List');
INSERT INTO fa_squad_status (status, description) VALUES ('MONITOR', 'Monitor');
INSERT INTO fa_squad_status (status, description) VALUES ('DO_NOT_MONITOR', 'Do Not Monitor');

INSERT INTO fa_squad (squad, description) VALUES ('SENIORS', 'Senior Squad');
INSERT INTO fa_squad (squad, description) VALUES ('U21', 'U21''s');
INSERT INTO fa_squad (squad, description) VALUES ('U20', 'U20''s');
INSERT INTO fa_squad (squad, description) VALUES ('U19', 'U19''s');
INSERT INTO fa_squad (squad, description) VALUES ('U18', 'U18''s');
INSERT INTO fa_squad (squad, description) VALUES ('U17', 'U17''s');
INSERT INTO fa_squad (squad, description) VALUES ('U16', 'U16''s');
INSERT INTO fa_squad (squad, description) VALUES ('U15', 'U15''s');

INSERT INTO fa_position (position_number, description) VALUES (1, 'Goalkeeper');
INSERT INTO fa_position (position_number, description) VALUES (2, 'Defender');
INSERT INTO fa_position (position_number, description) VALUES (3, 'Defender');
INSERT INTO fa_position (position_number, description) VALUES (4, 'Defender');
INSERT INTO fa_position (position_number, description) VALUES (5, 'Defender');
INSERT INTO fa_position (position_number, description) VALUES (6, 'Defender');
INSERT INTO fa_position (position_number, description) VALUES (7, 'Midfielder');
INSERT INTO fa_position (position_number, description) VALUES (8, 'Midfielder');
INSERT INTO fa_position (position_number, description) VALUES (9, 'Forward');
INSERT INTO fa_position (position_number, description) VALUES (10, 'Forward');
INSERT INTO fa_position (position_number, description) VALUES (11, 'Forward');

INSERT INTO fa_social_media (name, icon) VALUES ('TWITTER', null);
INSERT INTO fa_social_media (name, icon) VALUES ('FACEBOOK', null);
INSERT INTO fa_social_media (name, icon) VALUES ('INSTAGRAM', null);
INSERT INTO fa_social_media (name, icon) VALUES ('TRANSFER_MARKET', null);
INSERT INTO fa_social_media (name, icon) VALUES ('WIKIPEDIA', null);

INSERT INTO fa_grade (grade, description) VALUES ('A*', 'Player is of the most exceptional quality');
INSERT INTO fa_grade (grade, description) VALUES ('A', 'Player is almost exceptional');
INSERT INTO fa_grade (grade, description) VALUES ('B*', 'Player is ...');
INSERT INTO fa_grade (grade, description) VALUES ('B', null);
INSERT INTO fa_grade (grade, description) VALUES ('C*', null);
INSERT INTO fa_grade (grade, description) VALUES ('C', null);
INSERT INTO fa_grade (grade, description) VALUES ('M', null);

INSERT INTO fa_intel (intel_type) VALUES ('EDUCATION');
INSERT INTO fa_intel (intel_type) VALUES ('ELIGIBILITY');
INSERT INTO fa_intel (intel_type) VALUES ('GENERAL');

INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005278','AFC Bournemouth','BOU',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl001521','AFC Wimbledon','AFW',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl001326','Accrington Stanley','ASY',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl002457','Aldershot Town','ALD',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl002483','Alfreton Town',NULL,NULL,NULL,NULL,NULL,1959,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl002652','Altrincham','ALT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl003237','Arsenal','ARS',NULL,'London','Emirates Stadium','http://www.arsenal.com',1886,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl003354','Ashton United',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl003380','Aston Villa','AVL',NULL,NULL,NULL,NULL,1874,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004212','Barnet','BAT',NULL,NULL,NULL,NULL,1888,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004225','Barnsley','BAR',NULL,NULL,NULL,NULL,1887,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004251','Barrow','BRW',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004277','Barwell',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004342','Bath City',NULL,NULL,NULL,NULL,NULL,1889,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004706','Billericay Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004745','Birmingham City','BIR',NULL,NULL,NULL,NULL,1875,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004784','Blackburn Rovers','BLB',NULL,NULL,NULL,NULL,1875,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004797','Blackpool','BLP',NULL,NULL,NULL,NULL,1887,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004836','Blyth Spartans','BLY',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl004992','Bognor Regis Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005057','Bolton Wanderers','BOL',NULL,NULL,NULL,NULL,1880,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005109','Boreham Wood',NULL,NULL,NULL,NULL,NULL,1948,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005200','Boston United','BOS',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005317','Brackley Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005330','Bradford City','BRD',NULL,NULL,NULL,NULL,1903,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005343','Bradford Park Avenue','BPA',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005369','Braintree Town','BEE',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005460','Brentford','BRE',NULL,NULL,NULL,NULL,1889,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005499','Brighton and Hove Albion','BHA',NULL,NULL,NULL,NULL,1901,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005512','Bristol City','BCY',NULL,NULL,NULL,NULL,1897,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005525','Bristol City WFC','BCW',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005538','Bristol Rovers','BRI',NULL,NULL,NULL,NULL,1883,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005551','Bromley',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005785','Burnley','BRN','The Clarets','Burnley','Turf Moor','http://www.burnleyfootballclub.com/',1882,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005811','Burton Albion','BAL',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005837','Bury','BUR',NULL,NULL,NULL,NULL,1885,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005850','Buxton',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl005993','Cambridge United','CMU',NULL,NULL,NULL,NULL,1912,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006136','Cardiff City','CAR',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006162','Carlisle United','CUT',NULL,NULL,NULL,NULL,1903,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006682','Charlton Athletic','CHA',NULL,NULL,NULL,NULL,1905,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006708','Chelmsford City','CCY',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006721','Chelsea FC','CHE','The Blues','London','Stamford Bridge','http://www.chelseafc.com',1905,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006734','Cheltenham Town','CHT',NULL,NULL,NULL,NULL,1892,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006786','Chesham United','CHU',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006799','Chester FC','CHS',NULL,NULL,NULL,NULL,2010,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006812','Chesterfield','CHF',NULL,NULL,NULL,NULL,1866,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006929','Chippenham Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl006955','Chorley',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007267','Coalville Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007306','Colchester United','COU',NULL,NULL,NULL,NULL,1937,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007449','Concord Rangers','CON',NULL,NULL,NULL,NULL,1967,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007735','Coventry City','COV',NULL,NULL,NULL,NULL,1883,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007774','Crawley Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007852','Crewe Alexandra','CRE',NULL,NULL,NULL,NULL,1877,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl007969','Crystal Palace','CRY',NULL,NULL,NULL,NULL,1905,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl008177','Curzon Ashton',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl008268','Dagenham and Redbridge','DAG',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl008372','Darlington',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl008385','Dartford','DFD',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl008801','Derby County','DER',NULL,NULL,NULL,NULL,1884,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009113','Doncaster Rovers','DON',NULL,NULL,NULL,NULL,1879,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009165','Dover Athletic','DOV',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009464','East Thurrock United',NULL,NULL,NULL,NULL,NULL,1969,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009477','Eastbourne Borough','EAB',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009503','Eastleigh','ESL',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009516','Ebbsfleet United','EBU',NULL,NULL,NULL,NULL,1946,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl009776','England','ENG',NULL,NULL,NULL,NULL,NULL,'INTERNATIONAL',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl010075','Everton','EVE','The Toffees','Everton','Goodison Park','http://www.evertonfc.com/',1878,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl010127','Exeter City','EXE',NULL,NULL,NULL,NULL,1904,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl010205','Farsley Celtic',NULL,NULL,NULL,NULL,NULL,2010,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl011778','Fleetwood Town','FLT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl011908','Forest Green Rovers','FGR',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012272','Fulham','FUL',NULL,NULL,NULL,NULL,1879,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl001482','Fylde',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012298','Gainsborough Trinity',NULL,NULL,NULL,NULL,NULL,1873,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012376','Gateshead','GAT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012597','Gillingham','GIL',NULL,NULL,NULL,NULL,1893,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012766','Gloucester City',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl012961','Grantham Town','GRM',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013078','Grimsby Town','GRI',NULL,NULL,NULL,NULL,1878,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013273','Guiseley',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl010530','Halifax Town','HAL',NULL,NULL,NULL,NULL,1911,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013520','Hampton & Richmond','HPR',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013676','Harrogate Town','HGT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013689','Harrow Borough','HAR',NULL,NULL,NULL,NULL,1933,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013702','Hartlepool United','HAL',NULL,NULL,NULL,NULL,1908,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013728','Havant & Waterlooville','HWL',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013806','Hednesford Town','HDT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013858','Hemel Hempstead Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013923','Hereford FC',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl013949','Heybridge Swifts',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl014209','Huddersfield Town','HUD',NULL,NULL,NULL,NULL,1908,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl014235','Hull City','HUL',NULL,NULL,NULL,NULL,1904,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl014261','Hungerford Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl014339','Hyde United','HYD',NULL,NULL,NULL,NULL,1919,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl014820','Ipswich Town','IPS',NULL,NULL,NULL,NULL,1878,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl015808','Kidderminster Harriers','KID',NULL,NULL,NULL,NULL,1886,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016393','Lancaster City',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016562','Leamington','LEA',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016575','Leatherhead',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016627','Leeds United','LEE',NULL,NULL,NULL,NULL,1919,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016679','Leicester City','LEI',NULL,'Leicester','King Power Stadium','http://www.lcfc.com/',1884,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016809','Leyton Orient','LNO',NULL,NULL,NULL,NULL,1881,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016913','Lincoln City','LIN',NULL,NULL,NULL,NULL,1884,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl016991','Liverpool','LIV','The Reds','Liverpool','Anfield','http://www.liverpoolfc.tv',1892,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017394','Luton Town','LUT',NULL,NULL,NULL,NULL,1885,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017563','Macclesfield Town','MAC',NULL,NULL,NULL,NULL,1874,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017667','Maidenhead United','MHD',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017680','Maidstone United','MAI',NULL,NULL,NULL,NULL,1992,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017836','Manchester City Football Club','MCI',NULL,'Manchester','Etihad Stadium','mancity.com',1887,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017849','Manchester United','MUN','The Red Devils','Manchester','Old Trafford','http://www.manutd.com',1878,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017862','Mansfield Town','MAN',NULL,NULL,NULL,NULL,1897,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017901','Marine',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl017966','Matlock Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018161','Merstham',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018317','Mickleover Sports',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018343','Middlesbrough','MID',NULL,NULL,NULL,NULL,1875,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018408','Millwall','MIL',NULL,NULL,NULL,NULL,1885,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018538','Milton Keynes Dons','MKD',NULL,NULL,NULL,NULL,1889,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl018811','Morecambe','MOR',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019279','Nantwich Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019578','Newcastle United','NEW',NULL,'Newcastle','St James'' Park','https://www.nufc.co.uk/',1892,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019786','North Ferriby United',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019799','Northampton Town','NHT',NULL,NULL,NULL,NULL,1897,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019838','Norwich City','NOR',NULL,NULL,NULL,NULL,1902,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019851','Nottingham Forest','NFO',NULL,NULL,NULL,NULL,1865,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019864','Notts County','NOT',NULL,NULL,NULL,NULL,1862,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl019981','Nuneaton Town','NUN',NULL,NULL,NULL,NULL,2008,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl020150','Oldham Athletic','OLD',NULL,NULL,NULL,NULL,1895,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl020397','Opta Blue',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl020410','Opta White',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl020683','Oxford City',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl020696','Oxford United','OXF',NULL,NULL,NULL,NULL,1893,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021450','Peterborough United','PET',NULL,NULL,NULL,NULL,1934,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021723','Plymouth Argyle','PLY',NULL,NULL,NULL,NULL,1886,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021853','Poole Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021866','Port Vale','PTV',NULL,NULL,NULL,NULL,1876,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021918','Portsmouth','POR',NULL,NULL,NULL,NULL,1898,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021957','Prescot Cables',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl021983','Preston North End','PNE',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl022282','Queens Park Rangers','QPR',NULL,NULL,NULL,NULL,1885,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl022568','Reading','RDG',NULL,NULL,NULL,NULL,1871,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl023166','Rochdale','ROC',NULL,NULL,NULL,NULL,1907,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl023296','Rotherham United','RTH',NULL,NULL,NULL,NULL,1870,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl023439','Rushall Olympic',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl023621','Salford City',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl024440','Scunthorpe United','SCU',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl024817','Shaw Lane Association',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl024830','Sheffield United','SHU',NULL,NULL,NULL,NULL,1889,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl024843','Sheffield Wednesday','SHW',NULL,NULL,NULL,NULL,1867,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl024934','Shrewsbury Town','SHR',NULL,NULL,NULL,NULL,1886,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025337','Slough Town','SLT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025493','Solihull Moors',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025571','Southampton','SOU',NULL,NULL,NULL,NULL,1885,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025584','Southend United','STU',NULL,NULL,NULL,NULL,1906,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025597','Southport','SOT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl025714','Spennymoor Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026052','St Albans City','SAC',NULL,NULL,NULL,NULL,1908,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026169','Stafford Rangers',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026195','Stalybridge Celtic','STC',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026208','Stamford',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026286','Stevenage','STV',NULL,NULL,NULL,NULL,1976,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026338','Stockport County','SPT',NULL,NULL,NULL,NULL,1883,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026351','Stoke City','STK',NULL,NULL,NULL,NULL,1863,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026364','Stourbridge',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026494','Sunderland','SUN',NULL,NULL,NULL,NULL,1879,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026559','Sutton Coldfield Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026572','Sutton United','SUT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026728','Swansea City','SWA',NULL,NULL,NULL,NULL,1912,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026754','Swindon Town','SWI',NULL,NULL,NULL,NULL,1881,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl026949','Tamworth',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl027027','Taunton Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl001495','Telford United','TEL',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl027573','Torquay United','TOR',NULL,NULL,NULL,NULL,1899,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl027599','Tottenham Hotspur','TOT','Spurs','London','Wembley Stadium','http://www.tottenhamhotspur.com/',1882,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl027729','Tranmere Rovers','TRA',NULL,NULL,NULL,NULL,1884,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl027898','Truro City',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl011024','United of Manchester',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029809','Walsall','WLS',NULL,NULL,NULL,NULL,1888,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029835','Warrington Town','WRT',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029861','Watford','WAT',NULL,NULL,NULL,NULL,1881,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029874','Wealdstone',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029887','Welling United','WEL',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029900','West Bromwich Albion','WBA',NULL,NULL,NULL,NULL,1878,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029913','West Ham United','WHU',NULL,NULL,NULL,NULL,1895,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029939','Westfields',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029965','Weston-Super-Mare',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029978','Whitby Town',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl029991','Whitehawk',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030030','Wigan Athletic','WIG',NULL,NULL,NULL,NULL,1932,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030095','Witton Albion',NULL,NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030108','Woking','WOK',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030121','Wolverhampton Wanderers','WOL',NULL,NULL,NULL,NULL,1877,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030134','Workington','WOR',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030147','Wrexham','WRX',NULL,NULL,NULL,NULL,1872,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030173','Wycombe Wanderers','WYC',NULL,NULL,NULL,NULL,NULL,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030303','Yeovil Town','YEO',NULL,NULL,NULL,NULL,1895,'CLUB',true);
INSERT INTO fa_club (club_id, club_name, club_name_abbr, club_nickname, club_city, club_stadium, club_website, year_founded, team_type, is_active) VALUES ('facl030329','York City','YOR',NULL,NULL,NULL,NULL,1922,'CLUB',true);
